name: text-similarity

services:
  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    environment:
      ADDR: 0.0.0.0
      PORT: 8081
    ports:
      - 8081:8081

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - 8082:8082
