[package]
name = "text-similarity-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix-web = "4"
regex = "1.11.1"
once_cell = "1.20.2"

